name: Retrieve Vault Secret

on:
  push:
    branches:
      - main

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Vault CLI
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          token: ${{ secrets.VAULT_TOKEN }}
          url: https://1883-2a09-bac5-d46f-16c8-00-245-13.ngrok-free.app
          secrets: |
           secret/prods DASHBOARD_UI | DASHBOARD_UI
           
      - name: Retrieve Secret
        run: |
          DASHBOARD_UI = "${{ steps.import-secrets.outputs.DASHBOARD_UI }}"

      - name: Step following Import Secrets
        run: |
          touch secrets.json
          echo "${{ toJson(steps.import-secrets.outputs) }}" >> secrets.json
                
      - uses: actions/upload-artifact@v3
        name: Upload Artifact
        with:
         name: SecretsVariables
         path: "secrets.json"
 
