name: Retrieve Vault Secret

on:
  push:
    branches:
      - main

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Vault CLI
        uses: hashicorp/vault-action@v2
        with:
          token: ${{ secrets.VAULT_TOKEN }}
          url: ${{ secrets.VAULT_URL }}

      - name: Retrieve Secret
        id: import-secrets
        run: |
          export VAULT_ADDR=${{ secrets.VAULT_URL }}
          vault kv get -field=DASHBOARD_UI secret/prods > .env.tmp
          echo "DASHBOARD_UI=$(cat .env.tmp)" > .env

      - name: Display .env File
        run: |
          cat .env
