name: Retrieve Vault Secret

on:
  push:
    branches:
      - main

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Vault CLI
        uses: hashicorp/vault-action@v2
        with:
          token: ${{ secrets.VAULT_TOKEN }}
          url: https://1883-2a09-bac5-d46f-16c8-00-245-13.ngrok-free.app

      - name: Retrieve Secret
        run: |
          export VAULT_ADDR=${{ secrets.VAULT_URL }}
          DASHBOARD_UI=$(vault kv get -field=DASHBOARD_UI secret/prods)
          echo "DASHBOARD_UI=${DASHBOARD_UI}" > .env
           
      - uses: actions/upload-artifact@v3
        name: Upload Artifact
        with:
         name: SecretsVariables
         path: ".env"
 
