name: Retrieve Vault Secret

on:
  push:
    branches:
      - main

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Vault CLI
        uses: hashicorp/vault-action@v1
        with:
          vault-token: ${{ secrets.VAULT_TOKEN }}
          vault-url: ${{ secrets.VAULT_URL }}

      - name: Authenticate with Vault
        id: login
        uses: hashicorp/vault-login@v1
        with:
          method: token
          token: ${{ secrets.VAULT_TOKEN }}

      - name: Retrieve Secret
        run: |
          export VAULT_ADDR=${{ secrets.VAULT_URL }}
          export DASHBOARD_UI=$(vault kv get -field=DASHBOARD_UI secret/prods)
          echo "DASHBOARD_UI=${DASHBOARD_UI}" > .env

      - name: Display .env File
        run: |
          cat .env
