name: Retrieve Vault Secret

on:
  push:
    branches:
      - main

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Vault CLI
        uses: hashicorp/vault-action@v2
        with:
          vault-token: ${{ secrets.VAULT_TOKEN }}
          vault-url: ${{ secrets.VAULT_URL }}

      - name: Retrieve Secret
        run: |
          export VAULT_ADDR=${{ secrets.VAULT_URL }}
          vault kv get -field=DASHBOARD_UI secret/prods > .env

      - name: Display .env File
        run: cat .env
