name: Retrieve Vault Secret

on:
  push:
    branches:
      - main

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Vault CLI
        uses: hashicorp/vault-action@v2
        with:
          token: ${{ secrets.VAULT_TOKEN }}
          url: https://1883-2a09-bac5-d46f-16c8-00-245-13.ngrok-free.app

      - name: Retrieve Secret
        run: |
          export VAULT_ADDR=${{ secrets.VAULT_URL }}
          export VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}
          export SECRET_PATH=secret/prods
          export FIELD_NAME=DASHBOARD_UI
          export SECRET_URL="$VAULT_ADDR/v1/$SECRET_PATH"
          abc=$(curl -s --header "X-Vault-Token: $VAULT_TOKEN" $SECRET_URL | jq -r ".data.data.$FIELD_NAME")
          echo "abc=$abc" >> $GITHUB_ENV

      - name: Display Secret Value
        run: |
          echo "The secret value is $abc"
          
      - uses: actions/upload-artifact@v3
        name: Upload Artifact
        with:
         name: SecretsVariables
         path: "$abc"
 
