name: Retrieve Vault Secret

on:
  push:
    branches:
      - main

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Perform cURL request
        id: curl-request
        run: |
          response=$(curl -sSL --header "X-Vault-Token: hvs.BBSpQxhFT5NSQWwRkectS5KB" \
               --request GET \
               https://d1e5-2a09-bac5-d41b-16d2-00-246-a1.ngrok-free.app/v1/secret/data/prods)
          data=$(echo "$response" | jq -r '.data.data.DASHBOARD_UI')     
          echo "$data" > data.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: SecretsVariables
          path: data.txt
