name: Retrieve Vault Secret

on:
  push:
    branches:
      - main

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Vault CLI
        uses: hashicorp/setup-vault@v2
        with:
          vault-token: hvs.pZGVD0LmRE1EWw8HPGFAhrYa
          vault-url: https://1883-2a09-bac5-d46f-16c8-00-245-13.ngrok-free.app

      - name: Retrieve Secret
        run: |
          export VAULT_ADDR=https://1883-2a09-bac5-d46f-16c8-00-245-13.ngrok-free.app
          vault kv get -field=DASHBOARD_UI secret/prods > .env

      - name: Display .env File
        run: cat .env
